/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-19 02:55:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.demoweb.dto.BoardComment;
import com.demoweb.dto.Member;
import com.demoweb.dto.Board;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.demoweb.dto.Board");
    _jspx_imports_classes.add("com.demoweb.dto.BoardComment");
    _jspx_imports_classes.add("com.demoweb.dto.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>글쓰기</title>\r\n");
      out.write("\t<link rel=\"Stylesheet\" href=\"/demoweb/styles/default.css\" />\r\n");
      out.write("\t<link rel=\"Stylesheet\" href=\"/demoweb/styles/input2.css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t\t        function doDelete(boardNo, pageNo){\r\n");
      out.write("\t\t        \tyes = confirm(boardNo + '번 글을 삭제할까요 ?');\r\n");
      out.write("\t\t        \tif(yes){\r\n");
      out.write("\t\t        \t\tlocation.href = 'delete.action?boardno=' + boardNo + '&pageno='+ pageNo;\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t </script>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"pageContainer\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 pageContext.include("/WEB-INF/views/include/header.jsp"); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"padding-top:25px;text-align:center\">\r\n");
      out.write("\t\t<div id=\"inputcontent\">\r\n");
      out.write("\t\t    <div id=\"inputmain\">\r\n");
      out.write("\t\t        <div class=\"inputsubtitle\">게시판 글 내용</div>\r\n");
      out.write("\t\t        ");
 Board board = (Board)request.getAttribute("board"); 
      out.write("       \r\n");
      out.write("\t\t        <table>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>제목</th>\r\n");
      out.write("\t\t                <td>");
      out.print( board.getTitle() );
      out.write("</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>작성자</th>\r\n");
      out.write("\t\t                <td>");
      out.print( board.getWriter() );
      out.write("</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>작성일</th>\r\n");
      out.write("\t\t                <td>");
      out.print( board.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t                <th>조회수</th>\r\n");
      out.write("\t\t                <td>");
      out.print( board.getReadCount() );
      out.write("</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>내용</th>\r\n");
      out.write("\t\t                <td style=\"height:200px;vertical-align:top\">\t\t                    \r\n");
      out.write("\t\t                    ");
      out.print( board.getContent().replace("\r\n", "<br>").replace(" ", "&nbsp;") );
      out.write("\t\t                    \r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </table>\r\n");
      out.write("\t\t        ");
 Member member = (Member)session.getAttribute("loginuser"); 
      out.write("\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t        <div class=\"buttons\">\t\t        \r\n");
      out.write("\t\t         \t\r\n");
      out.write("\t\t         \t");
 if (member.getMemberId().equals(board.getWriter() )) {
      out.write("\r\n");
      out.write("\t\t         \t\t<a href='javaScript:doDelete(");
      out.print(board.getBoardNo() );
      out.write(',');
      out.write(' ');
      out.print(request.getAttribute("pageno") );
      out.write(")'>삭제</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t         \t\t<a href='edit.action?boardno=");
      out.print( board.getBoardNo());
      out.write("&pageno=");
      out.print(request.getAttribute("pageno"));
      out.write("'>수정</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t        \t");
 } else { 
      out.write("\r\n");
      out.write("\t\t        \t\t");
      out.write(" \r\n");
      out.write("\t\t        \t");
 } 
      out.write("\r\n");
      out.write("\t\t        \t\t<a href='replyform.action?borardno=");
      out.print(board.getBoardNo());
      out.write("&pageno=");
      out.print(request.getAttribute("pageno"));
      out.write("'>답글쓰기</a><br /><br />\r\n");
      out.write("                 \t\t<a href='list.action?pageno=");
      out.print( request.getAttribute("pageno"));
      out.write("'>목록보기</a>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<form id=\"commentform\" \r\n");
      out.write("\t\t\t\t\taction=\"writecomment.action\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"boardno\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print( board.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"pageno\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print( request.getAttribute("pageno") );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<table style=\"width:600px;border:solid 1px;margin:0 auto\">\r\n");
      out.write("\t\t\t            <tr>\r\n");
      out.write("\t\t\t                <td style=\"width:550px\">\t                \t\r\n");
      out.write("\t\t\t                    <textarea name=\"content\" \r\n");
      out.write("\t\t\t                    \tstyle=\"width:550px\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t                </td>\r\n");
      out.write("\t\t\t                <td style=\"width:50px;vertical-align:middle\">\r\n");
      out.write("\t\t\t                \t<a href=\"javascript:document.getElementById('commentform').submit();\"\r\n");
      out.write("\t\t\t                \t\tstyle=\"text-decoration:none\">\r\n");
      out.write("\t\t\t                \t\t댓글<br />등록\r\n");
      out.write("\t\t\t                \t</a>\r\n");
      out.write("\t\t\t                </td>\r\n");
      out.write("\t\t\t            </tr>                    \r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </form>        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <hr align=\"center\" style=\"width:600px;\" />\t\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        ");
 if (board.getComments().size() == 0) { 
      out.write("\r\n");
      out.write("\t\t        <h4 id=\"nodata\" style=\"text-align:center\">\r\n");
      out.write("\t\t            작성된 댓글이 없습니다.\r\n");
      out.write("\t\t        </h4>\r\n");
      out.write("\t\t        ");
 } else { 
      out.write("        \r\n");
      out.write("\t\t\t\t<!-- comment 표시 영역 -->\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tvar v = null, e = null;\r\n");
      out.write("\t\t\t\tfunction toggleCommentStatus(commentNo, edit){\r\n");
      out.write("\t\t\t\t\tif(v != null){\r\n");
      out.write("\t\t\t\t\t\tv.style.display = edit ? 'block' : 'none';\r\n");
      out.write("\t\t\t\t\t\te.style.display = edit ? 'none': 'block';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tv = document.getElementById(\"commentview\" + commentNo);\r\n");
      out.write("\t\t\t\t\te = document.getElementById(\"commentedit\" + commentNo);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tv.style.display = edit ? 'none' : 'block';\r\n");
      out.write("\t\t\t\t\te.style.display = edit ? 'block': 'none';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction deleteComment(commentNo, boardNo, pageNo){\r\n");
      out.write("\t\t\t\t\tvar yes = confirm(commentNo+\"번 댓글을 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(yes){\r\n");
      out.write("\t\t\t\t\t\tlocation.href = 'deletecomment.action?commentno=' + commentNo + '&boardno=' + boardNo + '&pageno='+pageNo;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<table style=\"width:600px;border:solid 1px;margin:0 auto\">\r\n");
      out.write("\t\t\t\t");
 for(BoardComment bcomment : board.getComments()) { 
      out.write("\r\n");
      out.write("\t\t        \t<tr>\r\n");
      out.write("\t\t        \t\t<td style=\"text-align:left;margin:5px;border-bottom: solid 1px\">\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t\t<div id='commentview");
      out.print( bcomment.getCommentNo() );
      out.write("'>\r\n");
      out.write("\t\t                    ");
      out.print( bcomment.getWriter() );
      out.write(" &nbsp;&nbsp;\r\n");
      out.write("\t\t                    [ ");
      out.print( bcomment.getRegDate() );
      out.write(" ]\r\n");
      out.write("\t\t                    <br /><br />\r\n");
      out.write("\t\t                    <span>\r\n");
      out.write("\t\t                        ");
      out.print( bcomment.getContent().replace("\r\n", "<br />") );
      out.write("\r\n");
      out.write("\t\t                    </span>\r\n");
      out.write("\t\t                    <br /><br />\r\n");
      out.write("\t\t                    ");

		                    String display = "";
		                    if (member.getMemberId().equals(bcomment.getWriter())) {
		                    	display = "block";//화면에 표시하세요
		                    } else {
		                    	display = "none";//화면에 표시하지 마세요
		                    }
		                    
		                   
		                    
      out.write("\r\n");
      out.write("\t\t                    <div style=\"display: ");
      out.print( display );
      out.write("\">\r\n");
      out.write("\t\t                    \t<a href=\"javascript:toggleCommentStatus(");
      out.print( bcomment.getCommentNo() );
      out.write(", true);\">편집</a>\r\n");
      out.write("\t\t                    \t&nbsp;\r\n");
      out.write("\t\t                    \t<a href=\"javascript:deleteComment(");
      out.print( bcomment.getCommentNo() );
      out.write(',');
      out.write(' ');
      out.print( board.getBoardNo() );
      out.write(',');
      out.write(' ');
      out.print( request.getAttribute("pageno") );
      out.write(")\">삭제</a>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <div id='commentedit");
      out.print( bcomment.getCommentNo() );
      out.write("' style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( bcomment.getWriter() );
      out.write("&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t[");
      out.print( bcomment.getRegDate() );
      out.write("] \r\n");
      out.write("\t\t\t\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"commenteditform");
      out.print( bcomment.getCommentNo() );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\taction=\"updatecomment.action\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"boardno\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( board.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pageno\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( request.getAttribute("pageno") );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"commentno\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( bcomment.getCommentNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"content\" style=\"width: 600px\" rows=\"3\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"200\">");
      out.print( bcomment.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:document.getElementById('commenteditform");
      out.print( bcomment.getCommentNo() );
      out.write("').submit();\">수정</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:toggleCommentStatus(");
      out.print( bcomment.getCommentNo() );
      out.write(", false);\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t</tr>\r\n");
      out.write("\t\t        ");
 } 
      out.write("\r\n");
      out.write("\t\t        </table>\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
