/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-18 05:51:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.demoweb.dto.Board;
import com.demoweb.dto.Member;

public final class editform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.demoweb.dto.Board");
    _jspx_imports_classes.add("com.demoweb.dto.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>글쓰기</title>\r\n");
      out.write("\t<link rel=\"Stylesheet\" href=\"/demoweb/styles/default.css\" />\r\n");
      out.write("\t<link rel=\"Stylesheet\" href=\"/demoweb/styles/input2.css\" />\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"pageContainer\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 pageContext.include("/WEB-INF/views/include/header.jsp"); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"padding-top:25px;text-align:center\">\r\n");
      out.write("\t\t<div id=\"inputcontent\">\r\n");
      out.write("\t\t    <div id=\"inputmain\">\r\n");
      out.write("\t\t        <div class=\"inputsubtitle\">게시판 글 수정</div>\r\n");
      out.write("\t\t        <form action=\"update.action\" \r\n");
      out.write("\t\t        \t  method=\"post\">\r\n");
      out.write("\t\t        ");
 Board board = (Board)request.getAttribute("board"); 
      out.write("\r\n");
      out.write("\t\t         <input type='hidden' name=\"boardno\" value=\"");
      out.print( board.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t\t        <table>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>제목</th>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                    <input type=\"text\" name=\"title\" style=\"width:480px\" value=\"");
      out.print(board.getTitle());
      out.write("\"/>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>작성자</th>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \t");
      out.print( ((Member)session.getAttribute("loginuser")).getMemberId() );
      out.write("\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t            </tr>\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>내용</th>\r\n");
      out.write("\t\t                <td>\t\t                    \r\n");
      out.write("\t\t                    <textarea \r\n");
      out.write("\t\t                    \tname=\"content\" cols=\"76\" rows=\"15\" >");
      out.print(board.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </table>\r\n");
      out.write("\t\t        <div class=\"buttons\">\r\n");
      out.write("\t\t        \t<!-- 아래 a 링크는 input type='submit' 버튼을 누르는 효과 발생 -->\t\t        \t\r\n");
      out.write("\t\t        \t<a href=\"javascript:document.forms[0].submit();\">글수정</a>\r\n");
      out.write("\t\t        \t&nbsp;&nbsp;\r\n");
      out.write("\t\t        \t      \r\n");
      out.write("\t\t        \t<a href='detail.action?boardno=");
      out.print(board.getBoardNo());
      out.write("&pageno=");
      out.print(request.getAttribute("pageno"));
      out.write("'>취소 </a>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>   \t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
