/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-22 04:38:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.dot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>Home</title>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar dot = document.getElementsByClassName(\"dot\");\r\n");
      out.write("\tvar input = document.getElementsByClassName(\"input\");\r\n");
      out.write("\tvar color = document.getElementsByClassName(\"color\");\r\n");
      out.write("\tvar currColor;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dotClick(event){\r\n");
      out.write("\t\tvar target = event.target;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(target.style.backgroundColor == \"white\"){\r\n");
      out.write("\t\t\ttarget.style.backgroundColor = currColor;\r\n");
      out.write("\t\t\tinput[target.id].value= currColor;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\ttarget.style.backgroundColor =\"white\";\r\n");
      out.write("\t\t\tinput[target.id].value='0';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   function gridRound(event){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdotClean();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar dotindex = 0;\r\n");
      out.write("\t\tfor(var i=0; i<1599; i++){\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    var dotX = parseInt(i%40);\r\n");
      out.write("\t\t    var dotY = parseInt(i/40);\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\tif( parseInt((dotX-5)*(dotX-5) + (dotY-5)*(dotY-5)) == parseInt(25) ){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvarindex[dotindex] = dotY*40 + dotX;\r\n");
      out.write("\t\t\t\talert(dotindex);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdotindex++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* alert(\"rot x: \" + resultX + \"rot y:\" + resultY); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i<varindex.length; i++) {\r\n");
      out.write("\t\t\tvar index = varindex[i];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdot[index].style.backgroundColor = \"black\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dotDisplay(event){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.write(\"<div align='center' style='margin-top: 30px'>\");\r\n");
      out.write("\t\tdocument.write(\"<table  border='2'>\");\r\n");
      out.write("\t\t");
for(int i = 0; i< 40; i++){
      out.write("\r\n");
      out.write("\t\t\tdocument.write(\"<tr>\")\r\n");
      out.write("\t\t\t");
for (int j =0; j< 40; j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.write(\"<td class='dot' id='");
      out.print((i*40)+j);
      out.write("' style='width: 10px; height: 10px; background-color: white;'></td>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\tdocument.write(\"</tr>\");\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t\tdocument.write(\"</table>\");\r\n");
      out.write("\t\t\tdocument.write(\"</div>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onload = function(event){\r\n");
      out.write("\t\t//dotDisplay();\r\n");
      out.write("\t\tfor(var i=0; i<dot.length; i++){\r\n");
      out.write("\t\t\tdot[i].addEventListener(\"click\", dotClick);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i<color.length; i++){\r\n");
      out.write("\t\t\tcolor[i].addEventListener(\"click\", function(event){\r\n");
      out.write("\t\t\t\tvar target = event.target;\r\n");
      out.write("\t\t\t\tcurrColor = target.style.backgroundColor;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<link rel=\"Stylesheet\" href=\"/demoweb/styles/default.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"pageContainer\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("background", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("palegreen", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"colorList\" style=\"float: left; margin-top: 30px\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #222222; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Black</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FFFF99; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Yellow</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FF9999; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Red</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #663300; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Brown</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FFCC00; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Pooh Yellow</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FF0000; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Vivid red</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FF5555; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Poket red</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: #FF6600; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Orange</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: skyblue; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Sky blue</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class='color' style=\"background-color: blue; width: 15px;height: 10px\"></td>\r\n");
      out.write("\t\t\t\t<td>Vivid blue</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div align='center' style='margin-top: 30px'>\r\n");
      out.write("\t\t<form id=\"registerform\" action=\"input.action\" method=\"post\"> \r\n");
      out.write("\t\t\t<table  border='2'>\r\n");
      out.write("\t\t\t\t");
for(int i = 0; i< 40; i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");
for (int j =0; j< 40; j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td class='dot' id='");
      out.print((i*40)+j);
      out.write("' style='width: 9px; height: 9px; background-color: white;'>\r\n");
      out.write("\t\t\t\t\t\t<input class='input' type='hidden' value='0' name='");
      out.print((i*40)+j);
      out.write("'/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"buttons\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"등록\" style=\"height:25px\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
