/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-11 07:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.demoweb.dto.Member;
import java.util.List;

public final class list2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.demoweb.dto.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <link rel=\"Stylesheet\" href=\"/demoweb/styles/default.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"pageContainer\">\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("       \t\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("        \t<br /><br />\r\n");
      out.write("        \t<div style='text-align:center'>\r\n");
      out.write("        \t\t[&nbsp;<a href=\"registerform.action\">사용자 등록</a>&nbsp;]\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t<br /><br />\r\n");
      out.write("        \t\r\n");
      out.write("        \t");
      out.write("\r\n");
      out.write("        \t");
 List<Member> members = 
        	  	(List<Member>)request.getAttribute("members"); 
      out.write("\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t<table text-align=\"center\" border=\"1\" align=\"center\" width=\"700px\">\r\n");
      out.write("        \t");
 for(Member member : members) { 
      out.write("\r\n");
      out.write("        \t\t<tr style=\"height:30px;background-color: hotpink;text-align:center;padding:5px\">\r\n");
      out.write("        \t\t\t<td style=\"width: 80px\">아이디 </td>\r\n");
      out.write("        \t\t\t<td style=\"width: 150px\">이메일</td>\r\n");
      out.write("        \t\t\t<td style=\"width: 80px\">사용자구분 </td>\r\n");
      out.write("        \t\t\t<td style=\"width: 80px\">활성화여부</td>\r\n");
      out.write("        \t\t\t<td style=\"width: 80px\">등록일자 </td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t<tr style=\"height:30px;\">\r\n");
      out.write("        \t\t\t<td style=\"padding:5px\">\r\n");
      out.write("        \t\t\t<a href = \"detail.action?memberid=");
      out.print( member.getMemberId() );
      out.write('"');
      out.write('>');
      out.print( member.getMemberId() );
      out.write("</a>\r\n");
      out.write("        \t\t\t</td>\r\n");
      out.write("        \t\t\t<td style=\"padding:5px\"> ");
      out.print( member.getEmail() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td style=\"padding:5px\">");
      out.print( member.getUserType() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td style=\"padding:5px\"> ");
      out.print( member.isActive() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td style=\"padding:5px\">");
      out.print( member.getRegDate() );
      out.write("</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("        \t</table>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
